### ISSUE TITLE
Konvertáló egyéb funkciók

### ISSUE THREAD

**Issue by SziliCs** [SziliCs/MeasureConverter#28]
A konvertáló egyéb funkcióinak (törlés, automatikus konvertálás, kijelentkezés) implementálása.

**Comment by SziliCs** [comment]
A törlést végző metódus elkészült. A további funkciók még kidolgozásra várnak.

**Comment by eengineer96** [comment]
Elkészítettem az osztály inicializálását, a nyomógombok listenerjét továbbá a kijelentkezést is megoldottam!
További feature request vagy bugfix esetén új issue indítása szükséges.
